controller_joint_names: ['', 'hip_joint1', 'shoulder_joint1', 'knee_joint1', 'hip_joint2', 'shoulder_joint2', 'knee_joint2', 'hip_joint3', 'shoulder_joint3', 'knee_joint3', 'hip_joint4', 'shoulder_joint4', 'knee_joint4', ]
